name: todo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  google_sign_in: ^6.1.4
  loading_animation_widget: ^1.2.0+4
  provider: ^6.0.5
  share_plus: ^7.0.2
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/bear.jpg
